blank_issues_enabled: false
contact_links:
  - name: Issue Guidelines
    url: https://github.com/Heisen47/itinerarly/issues/new/choose
    about: Use this template to create a properly formatted issue with guidelines
