name: Keep Server Awake

on:
  schedule:
    - cron: "*/10 * * * *" 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl ping
        run: |
          curl -s -f https://itinerarly-be.onrender.com || echo "Server ping failed"